name: Automerge

on:
  check_suite:
    types:
      - completed

jobs:
  automerge:
    name: automerge
    runs-on: ubuntu-latest
    steps:
      -
        name: Merge Dependabot Pull Request
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRESET: DEPENDABOT_MINOR
